### ISSUE TITLE
Add search field for Pokemon species selection

### ISSUE THREAD

**Issue by Zelxnte** [Azekthi/RibbonMasters#14]
I suppose this is more of a QoL improvement than anything else.

Mobile users aren't able to search through the list of Pokemon species like PC users are able to. 

The current selection feature is functional, although they can greatly benefit from a search function instead of scrolling through a long list of items.

**Comment by Azekthi** [comment]
Thank you for this suggestion, it's definitely useful for desktop as well but absolutely a requirement for better mobile support. I might have lumped this in with #6 but I'll try to make it happen sooner.

**Comment by Zelxnte** [comment]
I've managed to create a very simple search bar that goes through a given list of options, in pure HTML. 

Here's a small snippet of the code:

``` HTML
<form>
  <input list="speciesList" placeholder="Search..." />
    <datalist id="speciesList">
      <option value="Victreebel">
      <option value="Metapod">
      <option value="Treecko">
      <option value="Smeargle">
      <option value="Magikarp">
      <option value="Ditto">
  </datalist>
</form>
```

Here's a screenshot of it in action, with the original list of options:
![search-options-list](https://user-images.githubusercontent.com/21003803/200470264-73c0a716-eb42-48be-b050-187e9c83283d.png)

Based on the input, it looks for any matches which contain the search query within the options.

I've yet to integrate it with the original HTML file, although this may be of assistance to you.

**Comment by Azekthi** [comment]
The funny thing is, I was working on implementing a JS solution when you sent that reply :P

I did look into <datalist> but the problem there is that you can't easily restrict what the user puts in. It's used with <input> and not <select> so anyone could type anything in there. Theoretically, we could use JS to validate the input, but that would require iterating through a thousand array entries... We're already making use of JS anyway (a web app like this isn't possible otherwise) so using it to instead create a dynamic search for existing <select> is the better route.

Of course, then it gets hacky with the styling as I put in the commit... #6 is definitely high on the list as the next major improvement I need to do.
